export const SEARCH_FOCUS ="header/search_focus"
export const SEARCH_BLUR ="header/search_blur"
export const SEARCH_CHANGE ="header/search_change"
export const SEARCH_GET ="header/search_get"
export const GET_LIST_ERROR ="header/getList_error"
export const MOUSE_ENTER ="header/mouse_enter"
export const MOUSE_Leave ="header/mouse_leave"
export const CHANGE_PAGE ="header/change_page"